In [2]:

#Importar librerias? Pues claro que me importan!
import numpy as np
import pandas as pd
from numpy import random
from random import choices 
from scipy.stats import rv_discrete
import os 


In [2]:
#Definicion de variables 
mediaincubacion = 7
desvincubacion = 3
mediaduracion = 14
desvduracion = 5
posibilidadContagio = 0.4 #valor inicial, se puede cambiar 
cambioEstadoInicial = 15 
numpersonas = 800
personasedificio = 20
horassimulacion = 1200


In [5]:
#Definicion de una distribucion para la edad de las personas. Se basa en datos demograficos reales.
#Ahora mismo esta usando datos de España sacados del INE.
datos_edad = pd.read_csv("distribucion_edad.csv")
l=list(datos_edad.iloc[0])
l2= []
for i in range(len(l)-1):
    l2.append(int(l[i])/int(l[-1]))
#Esto es para ajustar porque parece que el numero total de personas y el numero de personas por edad no acaba de coincidir
#creo que es que corte los mayores de 100 años.
l2.append(1-sum(l2))

l3=[i for i in range(len(l2))]

#Esta es la distribución que obtenemos
dtrEdad = rv_discrete(values=(l3,l2))

#Elimino para que no queden variables sueltas
del l
del l2
del l3

In [3]:

def asintomatico_o_no():
    estado = ["asintomatico", "sintomatico"]
    peso_de_decision = [0.6, 0.4]
    n = choices(estado, peso_de_decision)
    return n[0]

def probabilidad_de_muerte(edad):
    if(edad > 65):
        valoracion = [0,1]
        peso = [0.87, 0.13] #queda pendiente revisar esto 
        n = choices(valoracion, peso)
    elif(edad <= 65):
        valoracion = [0,1]
        peso = [0.99, 0.01] #probabilidad que se correspende en caso que no tenga antecentes de ningun tipo
        n = choices(valoracion, peso) #n es un vector cuyo primer elemento es la valoracion 
    return n[0]
    

In [4]:
#Objeto que simula a una persona.
class Persona:
        def __init__(self, idpersona,edad,lugaroriginal, dni):           
            self.idpersona=idpersona
            self.edad=edad
            self.estadosposibles=["sano","incubando","incubandoContagioso","sintomatico","asintomatico","muerto","inmune"]
            self.estado=self.estadosposibles[0]
            self.lugar=lugaroriginal
            self.lugaroriginal=lugaroriginal
            self.diasestado=0 #esto se usa?
            self.cambioEstado=np.inf  #Atributo que indica que dia cambiara la persona de estado.
            self.contadorInfecciones=0
            self.dni = dni
            self.edificiomuerte=-1
            
             
           
        def __str__(self):
            #Devuelve un string con la informacion util del sujeto
            return str(self.idpersona) + "," + str(self.estado) + "," + str(self.lugar) + "," +str(self.dni) + "," +str(self.edad)            

        def puede_propagar(self):
            return ((self.estado == "sintomatico") or (self.estado == "asintomatico") or (self.estado == "incubandoContagioso"))
        def susceptible(self):
            return (self.estado == "sano")
        
        def esta_sano(self):
            return (self.estado == "sano") or (self.estado == "inmune")
        
        def infectar(self,posibilidadContagio,ciudad,mediaincubacion,desvincubacion,diaactual): #media y desv covid: 7.5 y 3.5
            if self.puede_propagar():
                for i in range(len(ciudad[self.lugar])): 
                    if (ciudad[self.lugar][i].susceptible()):
                        nocontagia=random.uniform(0, 1)   #Numero al azar, si es menor que la pos. de contagio, contagiara
                        if (nocontagia <posibilidadContagio/24):
                            ciudad[self.lugar][i].contagiarse(posibilidadContagio,ciudad,mediaincubacion,desvincubacion,diaactual)
                           # print(ciudad[self.lugar][i].cambioEstado)
                            self.contadorInfecciones +=1
                            
                            
        def contagiarse(self,posibilidadContagio,ciudad,mediaincubacion,desvincubacion,diaactual):
            self.estado=self.estadosposibles[1]
            self.diasestado=0
            self.cambioEstado=diaactual+(random.randint(int(mediaincubacion-desvincubacion),int(mediaincubacion+desvincubacion))/2)
                           
                            
        def transicionEstados(self, dia, mediaincubacion,desvincubacion,mediaduracion,desvduracion):
            #A partir de aqui se comprueba que estado posee la persona
            #Y se mira dos casos:
            #Si el dia del cambio de estado , coincide con el dia actual
            if(self.estado == "sintomatico"):
                me_voy_a_morir = probabilidad_de_muerte(self.edad)
                if(me_voy_a_morir == 1):
                    self.cambioEstado=np.inf
                    self.estado = "muerto"
            
            if(self.cambioEstado <= dia):
                if(self.estado == "incubando"):
                    self.estado = "incubandoContagioso" #se le asigna el siguiente estado  
                    self.cambioEstado = dia + random.randint(int(mediaincubacion-desvincubacion),int(mediaincubacion+desvincubacion))/2    #tiempo que pasa a inmune o muerto xD

                elif(self.estado == "incubandoContagioso"):
                    self.estado = asintomatico_o_no() #se le asigna el siguiente estado 
                    self.cambioEstado =dia+ random.randint(int(mediaduracion-desvduracion),int(mediaduracion+desvduracion)) #tiempo que pasa a inmune o muerto xD

                elif(self.estado == "sintomatico"):
                    self.cambioEstado = np.inf 
                    self.estado = "inmune"
                    '''
                      Y ahora una vez que pasa a ser asintomatico o no, se debe ver la probabilidad de que la persona se vaya 
                       a morir o no, y dependiendo de eso, se ha asignan unos dias...
                    '''

                elif(self.estado == "asintomatico"):
                    self.estado = "inmune"
                    self.cambioEstado = np.inf 
                                     
                

In [5]:

class Simulador:
        def __init__(self, numpersonas,personasedificio):           
            self.ciudad=crearciudadv0(numpersonas,personasedificio)
            self.dia=0 #se inicializa el dia con un valor de 0 
            self.hora=0 #se inicializa las horas con un valor de 0 
            self.numpersonasinicial=numpersonas 
            self.numpersonas=numpersonas
            self.numedificios=len(self.ciudad)
            self.capacidades=np.zeros(self.numedificios)
            self.CatalogoPersonas=[]
            self.cementerio=[]
            for i in range(self.numedificios-1,-1,-1):
                self.capacidades[i]=int(len(self.ciudad[i])) #establecemos las capacidades de los edificios
                for j in range (len(self.ciudad[i])):
                    self.CatalogoPersonas.append(self.ciudad[i][j])
                    
            self.capacidades=self.capacidades.astype(int)
            print(self.capacidades)
            #for i in range(len(self.CatalogoPersonas)):
            #    print(self.CatalogoPersonas[i])
            
                
           
        def __str__(self):
            #Devuelve un string con la informacion util del simulador
            return str(self.dia) + "," + str(self.hora) + "," + str(self.numpersonas) + "," +str(self.numedificios)  
        
        def actualizar_catalogo(self):#actualizamos los datos de las personas ordenadas por id
            nuevoCatalogo=[]
            for i in range(self.numedificios):
                for j in range (len(self.ciudad[i])):
                    nuevoCatalogo.append(self.ciudad[i][j]) #primero cogemos todas las personas sin ordenar
                    self.CatalogoPersonas = sorted(nuevoCatalogo, key=lambda x: x.idpersona, reverse=False)
            
        #Hace que el simulador avance una hora , con sus consecuencias en las personas
        def pasar_tiempo(self,mediaincubacion,desvincubacion,mediaduracion,desvduracion,posibilidadContagio ):
            if ((self.hora % 8)==0): #barajar a las personas cada 8 horas( hacen shuffle)
                self.moverpersonas2()
                #print("owo")
            for j in range(len(self.ciudad)): #recorre los edificios 
                for i in range(len(self.ciudad[j])): #recorre las personas 
                    self.ciudad[j][i].infectar(posibilidadContagio,self.ciudad,mediaincubacion,desvincubacion,self.dia) #pasa a infectar 
            if (self.hora<23):
                self.hora+=1
            else:#comienza un nuevo dia
                self.hora=0
                self.dia+=1
                for j in range(len(self.ciudad)):
                    for i in range(len(self.ciudad[j])):                     
                        self.ciudad[j][i].transicionEstados(self.dia, mediaincubacion,desvincubacion,mediaduracion,desvduracion)
                        
                for j in range(len(self.ciudad)):
                    for i in range(len(self.ciudad[j])-1,-1,-1):   
                        if (self.ciudad[j][i].estado=="muerto"):
                            
                            self.cementerio.append(self.ciudad[j].pop(i))
                            self.numpersonas-=1
                self.cementerio=sorted(self.cementerio, key=lambda x: x.idpersona, reverse=False)
                            
        
        #Función que devuelve el total de personas sanas o que ya pasaron la enfermedad de la ciudad
        def personas_sanas(self):
            contador_sanos=0
            for j in range(len(self.ciudad)): #se recorre los edificios de la ciudad
                    for i in range(len(self.ciudad[j])): #se va recorriendo las personas de los edificios 
                        if self.ciudad[j][i].esta_sano():
                            contador_sanos+=1
            return contador_sanos
        
        def cogerpersona(self, idpersona):
            self.actualizar_catalogo()
            return self.CatalogoPersonas[idpersona]
        
        
        
        def moverpersonas(self):#Baraja a todas las personas de la ciudad indiscriminadamente
                                #Vamos a crear una nueva ciudad utilizando las personas actuales
            print(f"Total de vivos:{self.numpersonas}")
            personasColocadas=0
            edificiosSinVaciar=self.numedificios
            ciudadnueva=[] #la nueva ciudad
            for i in range(self.numedificios-1,-1,-1):
                if (len(self.ciudad[i])==0):
                    del self.ciudad[i]
                    edificiosSinVaciar-=1
            
            for i in range(self.numedificios):
                edificionuevo = [] #El edificio actual de la ciudad nueva.
                
                for j in range(self.capacidades[i]):
                    if personasColocadas==self.numpersonas:
                        break
                    
                    if edificiosSinVaciar>1:
                        edificioescogido=random.randint(0,edificiosSinVaciar)
                    else:
                        edificioescogido=0
                    edificionuevo.append(self.ciudad[edificioescogido].pop(0))
                    edificionuevo[j].lugar=i
                    personasColocadas+=1
                    if (personasColocadas==self.numpersonas):
                        break
                    if (len(self.ciudad[edificioescogido])==0):
                        del  self.ciudad[edificioescogido]
                        edificiosSinVaciar-=1
            
                ciudadnueva.append(edificionuevo)
            self.ciudad=ciudadnueva
            
        def moverpersonas2(self):
            print(f"Total de vivos:{self.numpersonas}")
            personasColocadas=0
            edificiosAntiguos=self.numedificios
            ciudadnueva=[] #la nueva ciudad
            opciones=[]
            for i in range(self.numedificios):
                edificionuevo=[]
                ciudadnueva.append(edificionuevo)
                opciones.append(i)
            
            personasColocadas=0
            edificiosLlenos=self.numedificios
            
            for i in range(self.numedificios):
                for j in range(len(self.ciudad[i])):
                    if (len(self.ciudad[i])==0):
                        break
                    edificioALlenar=random.choice(opciones)
                    ciudadnueva[edificioALlenar].append(self.ciudad[i].pop(0))
                    if (len(ciudadnueva[edificioALlenar])==self.capacidades[edificioALlenar]):
                        opciones.remove(edificioALlenar)
            self.ciudad=ciudadnueva
            
            
        #Función que contagia a la primera persona (la deja sintomática), se usa para crear pacientes 0
        def contagio_fijo(self, cambioEstadoInicial):
            self.ciudad[0][0].estado=self.ciudad[0][0].estadosposibles[3]
            self.ciudad[0][0].cambioEstado= cambioEstadoInicial
            
            
        def mostrarcementerio(self):#pues eso
            print(f"Total de muertos:{len(self.cementerio)}")
            for j in range(len(self.cementerio)):
                print(self.cementerio[j])

In [6]:
#Funcion que se encarga de generar la edad de manera aleatoria
#Esta funcion ya no deberia ser necesaria
def generador_edad():
        n = dtrEdad.rvs(size=1) #el rango de edad, sera desde los 0 años hasta los 110
        return n


In [7]:
#Funcion que se encarga de generar numeros aleatorios 
def generador_numeros(longitud):
    numero=0
    for i in range(0,longitud): 
        n = random.randint(0,9)
        numero=10*numero+n
    return numero


In [8]:
#Funcion que se encarga de crear una secuencia valida de DNI
#Para ello, se ha utilizado el algoritmo que se usa en la vida real -en cuanto a la relacion numero y letra- 
def creaDni():
    letras = "TRWAGMYFPDXBNJZSQVHLCKEO" #conjunto de letras del dni
    input=generador_numeros(8)
    #Se consigue que toda la secuencia de numeros sea 1 solo
    
    #Se calcula la letra que ha de ser adicionada
    valor =int(input / 23)
    #print(f"El valor en este caso es: {valor}")
    valor *= 23
    valor = input - valor;
    #Ahora, ha de pasarse el numero de la secuencia
    #a una lista donde cada elemento es un numero de la secuencia 
    DNI=str(input)+letras[valor]
    
    return DNI

In [9]:
#Esta función crea la ciudad en la versión 0 de la simulacion.
#La ciudad es una lista de edificios y cada edificio es una lista de personas de tamaño variable.
#Input: personas de la ciudad, media de personas por edificio.
#Output: la ciudad.
def crearciudadv0(numpersonas,personasedificio):
    edificios = [] #La ciudad.
    capacidadusada=0 #Numero de personas metidas en la ciudad.
    edificioactual=0
    while (capacidadusada < numpersonas):
        column = [] #El edificio.
        esteedificio=random.randint(1,personasedificio*3) 
        '''
        Maximo de personas en el edificio. 
        Si usamos desviación tipica de capacidad de edificio, iria aqui
        '''
        contadoredificio=0 #numero de personas colocadas en este edificio
        #print(f"edificio actual:{edificioactual}")
        
        #Bucle en el que se llena el edificio de personas.
        while (capacidadusada < numpersonas) and (contadoredificio < esteedificio):
            
            #print(f"contador del edificio:{contadoredificio}")
            #print(f"capacidad:{esteedificio}")
            
            #Insercion de persona.
            column.append(Persona(capacidadusada,generador_edad(),edificioactual, creaDni()))
            capacidadusada+=1
            contadoredificio+=1
            
            
        #Insercion de edificio en la ciudad
        edificios.append(column)
        edificioactual+=1
        
    return edificios
def printearciudad(ciudad):        
    for j in range(len(ciudad)):
        for i in range(len(ciudad[j])):
            print(ciudad[j][i])
        print()        
        
#Funcion que dada la ciudad, y un indice, permite imprimir el edificio que corresponda a ese indice
def printearEdificio(ciudad , i):
     for j in range(len(ciudad[i])):
        print(ciudad[i][j])
    

In [10]:
MiSimulador=Simulador(numpersonas,personasedificio) #numPersonas, personasEdificio 
print(MiSimulador)
#se crea un paciente que resulta ser el 0, pasandole 15 dias como dia para el cambio de estadp 
MiSimulador.contagio_fijo(cambioEstadoInicial) 
for i in range(horassimulacion): #horas que pasa la simulacion 
    '''
    Datos inventados:
    MediaIncubación:7 dias
    DesvIncubación:3 dias
    MediaDuracion:14 dias
    DescDuracion:5 dias
    '''
    MiSimulador.pasar_tiempo(mediaincubacion,desvincubacion,mediaduracion,desvduracion,posibilidadContagio)
    if MiSimulador.hora==0:
        print("--------")
        print(" ")
        print(" ")
        print(MiSimulador.dia)
        print(MiSimulador.capacidades)
        print(MiSimulador)
        printearciudad(MiSimulador.ciudad)
        print(MiSimulador.personas_sanas())
        print(" ")
        print(" ")
        print("--------")
        print(" ")
        print(" ")
        MiSimulador.mostrarcementerio()
        print(" ")
        print(" ")
        print("--------")

[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
0,0,800,24
Total de vivos:800
Total de vivos:800
Total de vivos:800
--------
 
 
1
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
1,0,800,24
8,sano,1,76530624X,9
99,sano,3,41414605T,85
340,sano,11,16151626Z,83
212,sano,7,41014451T,46
603,sano,19,73458551R,53
798,sano,23,17863808F,83
195,sano,7,2448761C,78

396,sano,13,2714666E,47
54,sano,3,33333164T,65
670,sano,20,55245670S,8
517,sano,16,83320560R,41
791,sano,23,6555760R,35
640,sano,20,37527658F,66
19,sano,2,58256723T,1
70,sano,3,2026656B,77

732,sano,22,74767542Q,65
344,sano,11,34116508X,51
41,sano,2,55825572H,40
760,sano,22,11180366C,91
444,sano,14,8316802W,85
712,sano,21,3235362K,65
669,sano,20,84437277E,107
267,sano,9,5002021G,8
314,sano,10,8134074D,15
22,sano,2,68000253V,68
368,sano,12,34723524X,10
206,sano,7,88225347S,108
243,sano,8,58670546F,10
191,sano,6,60042352R,21
631,sano,20,41784118H,85
571,sano,18,35165801C,3
426,sano,13,6

586,sano,18,61067660S,72
672,sano,20,67144434M,92
210,sano,7,633621V,2
617,sano,19,66356267W,31
688,sano,21,42861478N,55
249,sano,9,37286006Q,100
402,sano,13,60314775N,73
499,sano,16,75522288V,106
664,sano,20,28387105E,29
522,sano,17,88813331G,69
283,sano,9,26036736T,56
490,sano,16,50081101G,109
139,sano,5,18716284B,2
159,sano,5,7422340X,74
225,sano,8,14830132P,17
140,sano,5,11151362L,1
574,sano,18,61208065M,52
306,sano,10,77511674H,23
681,sano,21,1172646Z,33

328,sano,11,41426211Z,87
465,incubando,15,67833287P,66
736,sano,22,5031642R,70
252,sano,9,8675453Z,36
84,sano,3,54737377E,35
461,sano,15,81533826E,65
39,sano,2,25307720S,18
226,sano,8,48872381A,70
51,sano,3,20570737C,92
782,sano,23,37735466X,22
792,sano,23,85213048A,60
678,sano,20,47462871W,16
759,sano,22,12370856F,36
514,sano,16,11610348V,20
111,sano,5,51455052G,4
692,sano,21,37047534P,79
790,sano,23,7702770R,36
702,sano,21,54061678V,55
95,sano,3,62184416Y,52
227,sano,8,28576548Z,37
256,sano,9,45334736B,35
364,sano,12,42443514G,

242,sano,8,40521727M,2
152,sano,5,57200150R,28
718,sano,22,54667266S,26
532,sano,17,20566883F,87
426,sano,13,61257866B,71
376,sano,12,41860725N,54
770,sano,22,8542034H,40
169,sano,6,66288721F,21
142,sano,5,3604031T,105
118,sano,5,53456288X,104
575,sano,18,52317584J,59
717,sano,22,60872252S,77
465,incubando,15,67833287P,66
64,sano,3,80885143P,38
314,sano,10,8134074D,15

456,sano,14,66236837B,26
485,sano,16,58364804G,37

562,sano,18,15872480L,91
288,sano,9,6426673J,75
177,sano,6,86410884E,44
494,sano,16,82184732M,84
478,sano,15,24656736T,59
385,sano,12,40122470M,33
112,sano,5,40124024H,24
612,sano,19,78342744Y,29
327,sano,11,67668021C,70
126,sano,5,71217013C,3
342,sano,11,43711226W,70
441,sano,14,24781086N,56
690,sano,21,37235880F,99
57,sano,3,35711865H,13
287,sano,9,47252266P,52
200,sano,7,71758575R,3
156,sano,5,60676673M,37
487,sano,16,13567146K,82
476,sano,15,81060865X,84
454,sano,14,70563284C,67
304,sano,10,83025268Y,68
715,sano,21,57144740K,98
150,sano,5,88202047Z,49
573,sano,18,658

76,sano,3,15304457G,62
688,sano,21,42861478N,55
168,sano,6,33821783F,96
524,sano,17,43421240T,82
551,sano,17,13632537T,86
500,sano,16,624482D,79
250,sano,9,3351635Y,46
26,sano,2,72170843V,35
283,sano,9,26036736T,56
512,sano,16,75105125M,90
719,sano,22,72755308Y,30
720,sano,22,25811265K,107
675,sano,20,82142540H,3
91,sano,3,83726675M,102
170,sano,6,50667831G,73
643,sano,20,48166148P,68
799,sano,23,82575530X,76
522,sano,17,88813331G,69
103,sano,3,43705555N,94

625,sano,20,41515185R,101
619,sano,19,22074864Q,24
192,sano,6,33258553R,9
404,sano,13,72321443J,53
107,sano,4,8647306L,26
179,sano,6,52053517D,87
106,sano,4,26310305F,45
83,sano,3,71762437E,83
492,sano,16,78458611E,22
199,sano,7,17632223D,47
239,sano,8,88050518D,56
529,sano,17,61105020T,70
560,sano,18,87225484P,7
293,sano,10,5548602J,16
351,sano,11,24185208H,65
299,sano,10,76042764A,82
738,sano,22,82535068M,102
88,sano,3,31037240M,54
95,sano,3,62184416Y,52

763,sano,22,26723568Y,38
270,sano,9,85231080A,104
637,sano,20,28034082A,60


404,sano,13,72321443J,53
398,sano,13,42528755F,103
744,sano,22,35444651H,75
378,sano,12,35262317M,100
438,sano,14,51132842R,1
149,sano,5,87725182P,97
538,sano,17,45836513C,92
241,sano,8,71748562Q,96
729,sano,22,44704886Q,71
54,sano,3,33333164T,65
416,sano,13,28331387X,22
145,sano,5,57844024J,65
524,sano,17,43421240T,82
323,sano,11,37421421F,59
91,sano,3,83726675M,102
350,sano,11,27283373Z,40
396,sano,13,2714666E,47
727,sano,22,87418784Q,70
648,sano,20,83626661H,63
753,sano,22,53451681A,54
413,sano,13,67426287Q,101
291,sano,10,24670880E,62
361,sano,11,72377615L,101
461,sano,15,81533826E,65
682,sano,21,82734538L,37
604,sano,19,41056208N,3
238,sano,8,40457312J,23
175,sano,6,53015428Z,55
263,sano,9,74241483J,87
796,sano,23,80578453T,33
646,sano,20,51804518P,59
407,sano,13,48081741B,58
157,sano,5,46503858C,12
10,sano,1,84781288E,78
65,sano,3,51747665B,14

740,sano,22,51306538R,29
349,sano,11,85443441M,51
605,sano,19,4605540C,27
534,sano,17,11004047L,77
163,sano,6,5805530P,2
208,sano,7,68286

Total de vivos:800
Total de vivos:800
--------
 
 
4
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
4,0,800,24
573,incubando,18,65820060V,64
790,sano,23,7702770R,36
334,sano,11,81060175X,62
246,sano,8,1774414X,39
311,sano,10,3800046D,100
215,sano,7,87723021D,100
464,sano,15,41677301J,70

389,sano,12,81337611C,69
679,sano,20,61826868Q,103
620,sano,19,80268668W,60
559,sano,17,31671174J,46
198,sano,7,11736168G,19
191,sano,6,60042352R,21
22,sano,2,68000253V,68
460,sano,15,21515768G,79

764,sano,22,14305422C,101
270,sano,9,85231080A,104
131,sano,5,15635332R,81
415,sano,13,85344130P,10
61,sano,3,41688821X,100
766,sano,22,62342657F,25
255,sano,9,50277424E,28
759,sano,22,12370856F,36
765,sano,22,52274362P,31
385,sano,12,40122470M,33
253,sano,9,58875344J,5
196,sano,7,85711525R,47
71,sano,3,25645002W,59
553,sano,17,27407723A,19
771,sano,22,17200354B,20
331,sano,11,75033435Y,79
716,sano,21,73211848L,78
444,sano,14,8316802W,85
554,sano,17,67115534Q,56
259,sano,9,25360842

600,sano,18,15140333P,61
364,sano,12,42443514G,65
488,sano,16,30117177B,102
48,sano,2,76521537P,20
178,sano,6,2863010Q,6
338,sano,11,56483744E,31
164,sano,6,84656203B,42
284,sano,9,27541308G,68
228,sano,8,25006358E,27
674,sano,20,38641502F,55
651,sano,20,1475712D,18

634,sano,20,54138728V,20
275,sano,9,50348203F,89
88,sano,3,31037240M,54
577,sano,18,18654632E,59
201,sano,7,54844003C,103
68,sano,3,38858567K,89
180,sano,6,3233842L,94
292,sano,10,68580611Q,17
608,sano,19,52087742X,13
403,sano,13,83500677M,90
446,sano,14,55613226P,98
234,sano,8,15737838L,95
148,sano,5,50144338Z,27
78,sano,3,16172854J,97
728,sano,22,60151161C,2
668,sano,20,65156472W,34
224,sano,8,62806253S,3
675,sano,20,82142540H,3
419,sano,13,30076061L,53
479,sano,15,20472517X,29
265,sano,9,30452570H,18
382,sano,12,52563825Q,11
175,sano,6,53015428Z,55
149,sano,5,87725182P,97
746,sano,22,66634801Y,109
323,sano,11,37421421F,59

618,sano,19,15135202Y,30
649,sano,20,67207271Y,4
657,sano,20,87420817W,77
221,sano,8,3414121R,23
5

Total de vivos:800
--------
 
 
5
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
5,0,800,24
0,sintomatico,0,13884278Y,20
101,sano,3,68845357D,11
36,incubando,2,78366765S,54
644,incubandoContagioso,20,47646551G,79
401,sano,13,76656020X,29
519,sano,16,24825600K,41
715,sano,21,57144740K,98

10,sano,1,84781288E,78
444,sano,14,8316802W,85
291,sano,10,24670880E,62
748,sano,22,88351107B,58
114,sano,5,11345320H,22
37,sano,2,88021316V,25
215,sano,7,87723021D,100
777,sano,23,32211330Z,75

442,sano,14,63223150Z,24
106,sano,4,26310305F,45
681,sano,21,1172646Z,33
286,sano,9,18056418S,48
721,sano,22,32421575Q,41
716,sano,21,73211848L,78
753,sano,22,53451681A,54
449,sano,14,57666825Y,93
696,sano,21,46557043Y,26
26,sano,2,72170843V,35
230,sano,8,81876522H,53
157,sano,5,46503858C,12
674,sano,20,38641502F,55
345,sano,11,6555406S,68
706,incubando,21,67580082X,0
778,sano,23,7220276R,105
153,sano,5,51845A,101
81,sano,3,63507548V,88
243,sano,8,58670546F,10
235,sano,8,3528682E,104


418,sano,13,67713425E,96
107,sano,4,8647306L,26
597,sano,18,77320764P,75
100,sano,3,82418868R,80
776,sano,23,36762002K,94
267,sano,9,5002021G,8
161,sano,5,54667005F,4
462,sano,15,40217786D,41
503,sano,16,63086638F,92
264,sano,9,41145615H,82
311,sano,10,3800046D,100
143,sano,5,11448883N,90
137,sano,5,75812234W,105
219,sano,8,50850818A,90
598,sano,18,48213246W,109

699,incubando,21,70830840V,104
312,sano,10,84426717L,96
34,incubando,2,17735572L,98
711,sano,21,75413680S,99
53,sano,3,42580263H,74
272,incubando,9,35128101V,73
327,sano,11,67668021C,70
738,sano,22,82535068M,102
266,sano,9,77341388R,36
213,incubando,7,40767854D,0
482,sano,15,38765371K,17
786,sano,23,141558Q,82
666,incubando,20,20515723E,8
524,incubando,17,43421240T,82
245,sano,8,27646552T,74
64,sano,3,80885143P,38
255,sano,9,50277424E,28
733,incubando,22,28523687F,97
129,sano,5,30533826S,54

705,sano,21,16808242A,52
237,sano,8,23126453E,50
771,sano,22,17200354B,20
408,sano,13,66570868J,54
77,incubando,3,14665804S,6
90,sano,3,1

307,sano,10,53674668M,74
159,sano,5,7422340X,74
743,sano,22,2656474C,18
746,sano,22,66634801Y,109
355,incubando,11,84865051L,71
541,sano,17,23044423X,27
192,sano,6,33258553R,9
145,sano,5,57844024J,65
66,sano,3,75208683V,97
106,sano,4,26310305F,45
599,sano,18,48305860H,40
373,sano,12,51241335A,16
23,sano,2,56651322E,15
744,incubando,22,35444651H,75
668,incubando,20,65156472W,34
475,sano,15,6416676K,48
725,sano,22,44582018Z,71
137,sano,5,75812234W,105
691,sano,21,65828182C,72
371,sano,12,55810733Z,49
185,sano,6,75281268Z,27
336,sano,11,86866525X,4
570,sano,18,41441485Q,77
589,incubandoContagioso,18,86663415J,59
585,sano,18,74362015W,17
554,incubando,17,67115534Q,56
456,sano,14,66236837B,26
418,sano,13,67713425E,96
785,sano,23,10783871E,86
452,sano,14,6241627W,83
292,sano,10,68580611Q,17

639,sano,20,56747576K,49
674,incubando,20,38641502F,55
738,sano,22,82535068M,102
399,incubando,13,67278835V,97
155,sano,5,41683137F,102
123,sano,5,46411628C,5
256,sano,9,45334736B,35
455,incubando,14,151

Total de vivos:800
Total de vivos:800
--------
 
 
7
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
7,0,800,24
756,incubando,22,86640234Q,14
129,sano,5,30533826S,54
799,incubando,23,82575530X,76
478,incubando,15,24656736T,59
148,incubando,5,50144338Z,27
176,sano,6,24826480G,46
376,incubando,12,41860725N,54

790,incubando,23,7702770R,36
487,incubando,16,13567146K,82
41,sano,2,55825572H,40
598,sano,18,48213246W,109
432,incubando,13,7751060Z,101
92,sano,3,76067782C,0
332,incubando,11,56481683P,93
338,incubando,11,56483744E,31

348,incubando,11,82113818T,107
160,incubando,5,34640048R,35
559,incubandoContagioso,17,31671174J,46
759,sano,22,12370856F,36
145,incubando,5,57844024J,65
524,incubando,17,43421240T,82
760,sano,22,11180366C,91
58,incubando,3,35850015F,98
456,sano,14,66236837B,26
583,incubando,18,75306187R,4
213,incubando,7,40767854D,0
594,incubando,18,33308730S,97
503,sano,16,63086638F,92
717,incubando,22,60872252S,77
400,sano,13,70165478E,56
27,incubando,2

Total de vivos:800
Total de vivos:800
--------
 
 
8
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
8,0,800,24
28,incubandoContagioso,2,42587584W,13
613,incubando,19,42525533M,34
485,incubandoContagioso,16,58364804G,37
121,incubando,5,7013136E,65
456,incubando,14,66236837B,26
477,incubando,15,3235624F,53
702,incubando,21,54061678V,55

115,incubando,5,78125530G,3
668,incubando,20,65156472W,34
799,incubando,23,82575530X,76
689,incubandoContagioso,21,24101128A,65
425,incubando,13,66454234N,48
455,incubandoContagioso,14,15110137B,36
721,incubando,22,32421575Q,41
413,incubando,13,67426287Q,101

33,sano,2,83530566V,21
678,incubando,20,47462871W,16
495,incubando,16,255636Z,15
572,sano,18,23830210W,54
280,sano,9,57384542W,12
398,incubando,13,42528755F,103
785,sano,23,10783871E,86
640,incubando,20,37527658F,66
6,incubando,0,18318322H,73
457,incubando,14,63233720G,20
245,incubando,8,27646552T,74
583,incubando,18,75306187R,4
91,incubando,3,83726675M,102
595,incubando,18

119,incubando,5,2404760H,37
220,sano,8,47047687Z,18
287,incubando,9,47252266P,52
741,incubando,22,6188165S,65
288,incubandoContagioso,9,6426673J,75
569,incubando,18,41226550Q,42
652,incubando,20,17200617K,10
29,incubando,2,62033464A,36
138,incubandoContagioso,5,87151463R,15
45,incubando,2,64385765W,22
225,incubando,8,14830132P,17

319,incubandoContagioso,11,78558328B,52
35,incubando,2,72702531Z,7
734,incubandoContagioso,22,70000332Q,33
493,incubando,16,31545447G,50
489,incubandoContagioso,16,23042638L,5
392,incubando,13,78357646G,86
449,incubando,14,57666825Y,93
403,sano,13,83500677M,90
632,incubando,20,16376675P,35
281,incubando,9,87348175V,32
340,incubando,11,16151626Z,83
339,incubando,11,52627435P,42
776,incubandoContagioso,23,36762002K,94
679,incubando,20,61826868Q,103
497,incubandoContagioso,16,46146713L,14
549,sano,17,86350122A,50
513,incubando,16,80673627T,33
650,incubandoContagioso,20,84565527R,87
568,incubandoContagioso,18,26412006W,109

205,incubando,7,7071004E,97
311,incuban

496,incubandoContagioso,16,80185780Y,5
103,incubandoContagioso,3,43705555N,94
464,incubandoContagioso,15,41677301J,70
666,incubandoContagioso,20,20515723E,8
42,incubando,2,65808476W,54
3,incubandoContagioso,0,16772702K,71
495,incubandoContagioso,16,255636Z,15
539,incubandoContagioso,17,13574016Z,86
479,incubandoContagioso,15,20472517X,29
55,incubando,3,44554301N,46
749,asintomatico,22,57478147C,40
280,incubando,9,57384542W,12
422,incubando,13,4344161J,53
187,incubando,6,84483407Z,33
184,incubando,6,2862315B,86
506,incubando,16,66654055D,84
304,incubando,10,83025268Y,68
36,incubandoContagioso,2,78366765S,54
215,incubandoContagioso,7,87723021D,100

636,incubando,20,4727565F,32
522,incubando,17,88813331G,69
51,incubando,3,20570737C,92
244,incubandoContagioso,8,21806043L,19
230,incubandoContagioso,8,81876522H,53
733,incubandoContagioso,22,28523687F,97
693,incubandoContagioso,21,37286531N,109
500,incubando,16,624482D,79
323,incubando,11,37421421F,59
401,incubando,13,76656020X,29
468,incuban

Total de vivos:800
Total de vivos:800
--------
 
 
11
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
11,0,799,24
142,asintomatico,5,3604031T,105
688,incubandoContagioso,21,42861478N,55
711,incubandoContagioso,21,75413680S,99
645,sintomatico,20,51248248Q,109
696,incubandoContagioso,21,46557043Y,26
281,incubandoContagioso,9,87348175V,32
303,incubandoContagioso,10,36477217E,17

116,incubandoContagioso,5,14233722B,12
518,incubandoContagioso,16,8367566M,48
327,incubandoContagioso,11,67668021C,70
697,incubandoContagioso,21,64743570L,74
143,incubandoContagioso,5,11448883N,90
320,incubandoContagioso,11,36360533V,89
159,incubando,5,7422340X,74
525,incubandoContagioso,17,2166185E,88

51,incubando,3,20570737C,92
194,asintomatico,7,5882521H,11
24,incubando,2,5385786Z,3
316,incubandoContagioso,11,4712408F,30
412,incubandoContagioso,13,34463765J,79
238,incubandoContagioso,8,40457312J,23
458,incubandoContagioso,14,12227122T,71
357,asintomatico,11,65216833B,37
153,sintomatic

258,incubandoContagioso,9,56148223W,39
771,incubandoContagioso,22,17200354B,20
594,incubandoContagioso,18,33308730S,97
179,incubandoContagioso,6,52053517D,87
291,incubandoContagioso,10,24670880E,62
439,incubandoContagioso,14,13715512Z,87

398,incubandoContagioso,13,42528755F,103
792,asintomatico,23,85213048A,60
626,incubandoContagioso,20,37685176K,44
561,incubandoContagioso,18,37217571Y,37
642,incubandoContagioso,20,44021524F,72
41,incubandoContagioso,2,55825572H,40
639,incubandoContagioso,20,56747576K,49
273,incubandoContagioso,9,16487823C,0
229,incubandoContagioso,8,38133583C,73
50,incubandoContagioso,3,1138315E,33
615,incubando,19,67008382K,43
778,asintomatico,23,7220276R,105
751,sintomatico,22,37746831J,72
277,sintomatico,9,60018311H,77
721,incubandoContagioso,22,32421575Q,41
558,asintomatico,17,5480211R,1
486,incubandoContagioso,16,23620161N,67
64,incubandoContagioso,3,80885143P,38
16,incubandoContagioso,2,42577074A,44

11,incubandoContagioso,1,34837711W,34
609,incubandoContagioso

379,sintomatico,12,68384740J,105
656,asintomatico,20,42148522X,109
323,incubandoContagioso,11,37421421F,59
769,incubandoContagioso,22,12822071P,22
352,sintomatico,11,54247521C,65
457,incubandoContagioso,14,63233720G,20
553,sintomatico,17,27407723A,19
446,sintomatico,14,55613226P,98
560,sintomatico,18,87225484P,7

725,incubandoContagioso,22,44582018Z,71
537,asintomatico,17,56282136D,26
529,incubandoContagioso,17,61105020T,70
259,incubandoContagioso,9,25360842F,102
329,sintomatico,11,70681520J,102
209,incubandoContagioso,7,16131278K,100
429,sintomatico,13,87505714Y,76
132,incubandoContagioso,5,72326021Z,94
564,incubandoContagioso,18,6003774S,64
713,incubandoContagioso,21,7356623G,36
366,incubandoContagioso,12,66057584C,74
415,incubandoContagioso,13,85344130P,10
288,sintomatico,9,6426673J,75
728,incubandoContagioso,22,60151161C,2
293,sintomatico,10,5548602J,16
788,incubandoContagioso,23,42171634F,16
547,sintomatico,17,31373211S,107
136,incubandoContagioso,5,11387366C,90
453,asintomatico,1

351,asintomatico,11,24185208H,65
690,asintomatico,21,37235880F,99
716,sintomatico,21,73211848L,78
767,asintomatico,22,38161657B,56
226,asintomatico,8,48872381A,70
561,asintomatico,18,37217571Y,37
89,asintomatico,3,86030854K,109
106,asintomatico,4,26310305F,45
52,asintomatico,3,48423534R,25
775,asintomatico,22,42800623S,65
669,asintomatico,20,84437277E,107
470,incubandoContagioso,15,503605C,53
507,asintomatico,16,64652807Z,88
556,incubandoContagioso,17,73137088D,69
461,incubandoContagioso,15,81533826E,65
499,incubandoContagioso,16,75522288V,106
685,incubandoContagioso,21,43117360L,3
195,asintomatico,7,2448761C,78
603,asintomatico,19,73458551R,53
165,incubandoContagioso,6,27808357T,87

696,sintomatico,21,46557043Y,26
110,incubandoContagioso,5,81034501G,8
662,asintomatico,20,15207748X,33
398,incubandoContagioso,13,42528755F,103
243,sintomatico,8,58670546F,10
717,incubandoContagioso,22,60872252S,77
671,incubandoContagioso,20,13067242E,64
260,asintomatico,9,36173243Q,79
514,incubandoContagi

Total de vivos:792
--------
 
 
14
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
14,0,778,24
249,asintomatico,9,37286006Q,100
315,asintomatico,10,44112037S,51
609,asintomatico,19,74768710B,99
121,incubandoContagioso,5,7013136E,65
79,sintomatico,3,533082B,42
5,incubandoContagioso,0,73024747T,107
425,asintomatico,13,66454234N,48

88,asintomatico,3,31037240M,54
548,asintomatico,17,43781426Y,63
101,asintomatico,3,68845357D,11
559,asintomatico,17,31671174J,46
706,asintomatico,21,67580082X,0
39,sintomatico,2,25307720S,18
527,asintomatico,17,23070677K,17
1,asintomatico,0,50160011R,4

702,sintomatico,21,54061678V,55
128,incubandoContagioso,5,86888700J,65
298,incubandoContagioso,10,54344368Z,94
118,sintomatico,5,53456288X,104
576,incubandoContagioso,18,3732648R,79
628,sintomatico,20,82885713S,5
397,sintomatico,13,88641310T,36
518,asintomatico,16,8367566M,48
552,asintomatico,17,47544A,100
508,asintomatico,16,48210667E,34
44,asintomatico,2,65608264M,75
632,sintomatico,

193,asintomatico,7,26526044Y,56
555,asintomatico,17,45306170B,40
500,incubandoContagioso,16,624482D,79
749,asintomatico,22,57478147C,40
640,incubandoContagioso,20,37527658F,66
796,sintomatico,23,80578453T,33
326,asintomatico,11,70835381G,85
185,sintomatico,6,75281268Z,27
484,asintomatico,15,5478571V,5
489,sintomatico,16,23042638L,5
237,sintomatico,8,23126453E,50

410,asintomatico,13,82403687T,79
745,sintomatico,22,56036852C,108
270,asintomatico,9,85231080A,104
607,asintomatico,19,84746250J,107
735,incubandoContagioso,22,45245148P,36
417,sintomatico,13,20717372F,49
734,asintomatico,22,70000332Q,33
311,asintomatico,10,3800046D,100
690,asintomatico,21,37235880F,99
361,asintomatico,11,72377615L,101
27,sintomatico,2,31206428M,47
474,incubandoContagioso,15,10310870Q,17
492,asintomatico,16,78458611E,22
96,incubandoContagioso,3,41311551D,27
536,asintomatico,17,65703878P,3
764,sintomatico,22,14305422C,101
366,incubandoContagioso,12,66057584C,74
276,sintomatico,9,56481150G,0
105,incubandoContagi

675,asintomatico,20,82142540H,3
719,asintomatico,22,72755308Y,30
734,asintomatico,22,70000332Q,33
107,sintomatico,4,8647306L,26
772,asintomatico,22,46026578J,55
317,sintomatico,11,81718070J,25
315,asintomatico,10,44112037S,51
70,sintomatico,3,2026656B,77
227,asintomatico,8,28576548Z,37
250,incubandoContagioso,9,3351635Y,46

169,asintomatico,6,66288721F,21
343,incubandoContagioso,11,87754888K,12
23,sintomatico,2,56651322E,15
449,sintomatico,14,57666825Y,93
441,asintomatico,14,24781086N,56
541,asintomatico,17,23044423X,27
532,asintomatico,17,20566883F,87
174,sintomatico,6,44708426Z,33
393,asintomatico,13,8070715S,82
410,asintomatico,13,82403687T,79
357,asintomatico,11,65216833B,37
94,incubandoContagioso,3,65162407A,25
324,asintomatico,11,55773387C,77
135,asintomatico,5,22766220S,4
730,asintomatico,22,18720748J,24
652,asintomatico,20,17200617K,10
474,sintomatico,15,10310870Q,17
688,asintomatico,21,42861478N,55
108,asintomatico,5,14220578T,37
583,asintomatico,18,75306187R,4
223,sintomatico

Total de vivos:759
--------
 
 
16
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
16,0,750,24
382,asintomatico,12,52563825Q,11
102,sintomatico,3,50457710B,59
708,sintomatico,21,30568531J,75
40,asintomatico,2,708562R,89
312,asintomatico,10,84426717L,96
376,sintomatico,12,41860725N,54
76,asintomatico,3,15304457G,62

27,sintomatico,2,31206428M,47
499,asintomatico,16,75522288V,106
115,sintomatico,5,78125530G,3
171,asintomatico,6,11376657Y,67
170,sintomatico,6,50667831G,73
583,asintomatico,18,75306187R,4
603,asintomatico,19,73458551R,53
186,asintomatico,6,46524077E,79

765,sintomatico,22,52274362P,31
576,sintomatico,18,3732648R,79
448,sintomatico,14,37418676E,66
337,asintomatico,11,10232331E,101
195,asintomatico,7,2448761C,78
649,sintomatico,20,67207271Y,4
472,asintomatico,15,50004015Z,3
793,asintomatico,23,37742808S,40
353,asintomatico,11,58161703Q,41
695,asintomatico,21,87017841D,74
663,asintomatico,20,64485734J,89
287,asintomatico,9,47252266P,52
539,asintomatic

Total de vivos:750
Total de vivos:750
--------
 
 
17
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
17,0,738,24
472,asintomatico,15,50004015Z,3
373,asintomatico,12,51241335A,16
418,sintomatico,13,67713425E,96
416,asintomatico,13,28331387X,22
160,sintomatico,5,34640048R,35
75,asintomatico,3,67514254P,97
693,asintomatico,21,37286531N,109

430,asintomatico,13,77855386H,94
23,sintomatico,2,56651322E,15
636,asintomatico,20,4727565F,32
795,asintomatico,23,84333865H,100
100,asintomatico,3,82418868R,80
534,asintomatico,17,11004047L,77
353,asintomatico,11,58161703Q,41
715,asintomatico,21,57144740K,98

628,sintomatico,20,82885713S,5
325,sintomatico,11,25234050Z,91
518,asintomatico,16,8367566M,48
108,asintomatico,5,14220578T,37
470,asintomatico,15,503605C,53
718,asintomatico,22,54667266S,26
432,sintomatico,13,7751060Z,101
701,asintomatico,21,27310842K,57
85,sintomatico,3,51122384P,8
411,asintomatico,13,80705542Z,2
10,sintomatico,1,84781288E,78
734,asintomatico,22,70000

Total de vivos:738
--------
 
 
18
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
18,0,728,24
115,sintomatico,5,78125530G,3
725,asintomatico,22,44582018Z,71
183,asintomatico,6,26202006S,109
195,asintomatico,7,2448761C,78
226,asintomatico,8,48872381A,70
53,sintomatico,3,42580263H,74
507,asintomatico,16,64652807Z,88

546,asintomatico,17,61363166V,71
230,asintomatico,8,81876522H,53
248,asintomatico,9,71130426M,56
28,asintomatico,2,42587584W,13
446,sintomatico,14,55613226P,98
187,asintomatico,6,84483407Z,33
591,sintomatico,18,20001612F,0
644,sintomatico,20,47646551G,79

753,asintomatico,22,53451681A,54
223,sintomatico,8,3838858C,33
82,asintomatico,3,77836523S,42
405,asintomatico,13,28202185E,75
104,sintomatico,3,84674306J,84
338,asintomatico,11,56483744E,31
350,sintomatico,11,27283373Z,40
598,asintomatico,18,48213246W,109
537,asintomatico,17,56282136D,26
371,asintomatico,12,55810733Z,49
372,sintomatico,12,41036521J,65
677,asintomatico,20,77033654F,29
242,sintomat

522,asintomatico,17,88813331G,69
145,asintomatico,5,57844024J,65
779,asintomatico,23,88864105V,101
353,asintomatico,11,58161703Q,41
414,sintomatico,13,65516006T,93
432,sintomatico,13,7751060Z,101
566,asintomatico,18,88804531J,86
429,sintomatico,13,87505714Y,76
348,asintomatico,11,82113818T,107
290,sintomatico,9,12623048G,53
731,asintomatico,22,17066652P,99
159,asintomatico,5,7422340X,74
311,asintomatico,10,3800046D,100
532,asintomatico,17,20566883F,87
232,sintomatico,8,14855377E,81
364,sintomatico,12,42443514G,65
580,asintomatico,18,61087185J,3
577,asintomatico,18,18654632E,59
795,asintomatico,23,84333865H,100
295,asintomatico,10,58674080E,50
315,asintomatico,10,44112037S,51
13,asintomatico,1,40467652A,97

3
 
 
--------
 
 
Total de muertos:72
10,muerto,1,84781288E,78
15,muerto,2,36121484F,104
47,muerto,2,12176403L,86
59,muerto,3,26024564H,66
66,muerto,3,75208683V,97
67,muerto,3,22001017E,86
74,muerto,3,73464544Z,108
80,muerto,3,73625082N,72
87,muerto,3,10254348M,69
91,muerto,3,837266

--------
 
 
20
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
20,0,708,24
28,asintomatico,2,42587584W,13
490,asintomatico,16,50081101G,109
640,asintomatico,20,37527658F,66
50,asintomatico,3,1138315E,33
440,sintomatico,14,34576715X,65
105,asintomatico,3,28115443J,0
92,asintomatico,3,76067782C,0

106,asintomatico,4,26310305F,45
299,asintomatico,10,76042764A,82
667,asintomatico,20,1288608X,66
742,sintomatico,22,56037884V,91
379,sintomatico,12,68384740J,105
330,sintomatico,11,32471137J,57
134,asintomatico,5,12232543Q,48
575,asintomatico,18,52317584J,59

174,sintomatico,6,44708426Z,33
444,asintomatico,14,8316802W,85
405,asintomatico,13,28202185E,75
261,asintomatico,9,26624476K,99
307,asintomatico,10,53674668M,74
642,asintomatico,20,44021524F,72
694,asintomatico,21,84286180N,98
517,sintomatico,16,83320560R,41
402,asintomatico,13,60314775N,73
781,asintomatico,23,47788014V,58
719,asintomatico,22,72755308Y,30
421,asintomatico,13,1835120L,1
85,sintomatico,3,51122384P,

381,sintomatico,12,6384740D,96
8,inmune,1,76530624X,9
512,asintomatico,16,75105125M,90
533,asintomatico,17,36015627L,61
242,sintomatico,8,40521727M,2
626,asintomatico,20,37685176K,44
248,asintomatico,9,71130426M,56
619,sintomatico,19,22074864Q,24
250,sintomatico,9,3351635Y,46
184,asintomatico,6,2862315B,86
456,asintomatico,14,66236837B,26

692,sintomatico,21,37047534P,79
328,asintomatico,11,41426211Z,87
114,sintomatico,5,11345320H,22
11,sintomatico,1,34837711W,34
61,asintomatico,3,41688821X,100
16,asintomatico,2,42577074A,44
278,asintomatico,9,47138042W,66
89,asintomatico,3,86030854K,109
515,sintomatico,16,35853238X,90
135,asintomatico,5,22766220S,4
549,asintomatico,17,86350122A,50
703,sintomatico,21,35845665G,9
270,asintomatico,9,85231080A,104
180,asintomatico,6,3233842L,94
235,sintomatico,8,3528682E,104
791,sintomatico,23,6555760R,35
669,asintomatico,20,84437277E,107
506,asintomatico,16,66654055D,84
788,asintomatico,23,42171634F,16
290,sintomatico,9,12623048G,53
166,sintomatico,6,531

443,muerto,14,37865288C,73
447,muerto,14,67576300T,107
448,muerto,14,37418676E,66
464,muerto,15,41677301J,70
476,muerto,15,81060865X,84
510,muerto,16,12420486A,98
525,muerto,17,2166185E,88
530,muerto,17,25452426M,69
538,muerto,17,45836513C,92
542,muerto,17,44865035Q,105
543,muerto,17,11602863F,95
547,muerto,17,31373211S,107
565,muerto,18,23125751X,77
576,muerto,18,3732648R,79
593,muerto,18,35710871J,84
597,muerto,18,77320764P,75
624,muerto,20,45650242A,107
638,muerto,20,16257716M,67
639,muerto,20,56747576K,49
645,muerto,20,51248248Q,109
653,muerto,20,31448805P,98
657,muerto,20,87420817W,77
659,muerto,20,80804752W,79
665,muerto,20,74655483J,96
676,muerto,20,27400810J,79
686,muerto,21,46863535T,82
697,muerto,21,64743570L,74
711,muerto,21,75413680S,99
716,muerto,21,73211848L,78
727,muerto,22,87418784Q,70
745,muerto,22,56036852C,108
746,muerto,22,66634801Y,109
755,muerto,22,63868036A,91
764,muerto,22,14305422C,101
780,muerto,23,48146311C,67
790,muerto,23,7702770R,36
799,muerto,23,82575530X

121,sintomatico,5,7013136E,65
512,asintomatico,16,75105125M,90
370,sintomatico,12,14070732E,44
301,asintomatico,10,57240603C,62
591,inmune,18,20001612F,0
209,asintomatico,7,16131278K,100
119,sintomatico,5,2404760H,37
517,sintomatico,16,83320560R,41
214,sintomatico,7,75304148D,40
248,inmune,9,71130426M,56
79,sintomatico,3,533082B,42
358,asintomatico,11,33077340M,23
18,asintomatico,2,45852444N,95
707,sintomatico,21,24402224Y,27
77,asintomatico,3,14665804S,6
486,sintomatico,16,23620161N,67
488,asintomatico,16,30117177B,102
644,inmune,20,47646551G,79

363,asintomatico,12,75886208P,23
256,sintomatico,9,45334736B,35
210,sintomatico,7,633621V,2
528,asintomatico,17,84444257X,61
34,asintomatico,2,17735572L,98
484,asintomatico,15,5478571V,5
173,asintomatico,6,6466528D,76
308,asintomatico,10,17115748E,90
32,inmune,2,57815433B,80
767,asintomatico,22,38161657B,56
634,asintomatico,20,54138728V,20
232,inmune,8,14855377E,81
106,inmune,4,26310305F,45
128,asintomatico,5,86888700J,65
174,inmune,6,4470842

452,sintomatico,14,6241627W,83
358,asintomatico,11,33077340M,23
730,inmune,22,18720748J,24
439,asintomatico,14,13715512Z,87
227,asintomatico,8,28576548Z,37
564,asintomatico,18,6003774S,64
744,asintomatico,22,35444651H,75
754,sintomatico,22,40876731G,45
61,inmune,3,41688821X,100
85,sintomatico,3,51122384P,8
584,inmune,18,23462113C,90
214,sintomatico,7,75304148D,40
737,asintomatico,22,72743210Y,91
729,inmune,22,44704886Q,71
422,asintomatico,13,4344161J,53
472,asintomatico,15,50004015Z,3
599,inmune,18,48305860H,40
685,sintomatico,21,43117360L,3
360,asintomatico,11,70316188J,97

371,asintomatico,12,55810733Z,49
609,asintomatico,19,74768710B,99
558,asintomatico,17,5480211R,1
197,sintomatico,7,87550250Z,24
283,inmune,9,26036736T,56
4,asintomatico,0,28015837C,31
504,asintomatico,16,85435387R,94
417,inmune,13,20717372F,49
741,asintomatico,22,6188165S,65
21,inmune,2,37047443D,104
582,asintomatico,18,28525816C,68
781,asintomatico,23,47788014V,58
516,asintomatico,16,57531232K,54
192,asintomatico,

Total de vivos:689
Total de vivos:689
--------
 
 
24
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
24,0,684,24
113,inmune,5,22123455P,100
374,asintomatico,12,36321821Z,4
344,asintomatico,11,34116508X,51
474,sintomatico,15,10310870Q,17
425,asintomatico,13,66454234N,48
182,asintomatico,6,47155885C,51
761,asintomatico,22,82184205F,72

380,sintomatico,12,72470108Y,32
114,sintomatico,5,11345320H,22
497,inmune,16,46146713L,14
635,asintomatico,20,81076160X,60
292,inmune,10,68580611Q,17
751,inmune,22,37746831J,72
483,inmune,15,53135616G,106
732,asintomatico,22,74767542Q,65

604,inmune,19,41056208N,3
253,sintomatico,9,58875344J,5
104,sintomatico,3,84674306J,84
274,asintomatico,9,6271152H,14
595,asintomatico,18,35758087X,60
381,sintomatico,12,6384740D,96
781,asintomatico,23,47788014V,58
477,inmune,15,3235624F,53
410,inmune,13,82403687T,79
198,sintomatico,7,11736168G,19
262,asintomatico,9,44552465Q,81
324,asintomatico,11,55773387C,77
359,asintomatico,11,72663238M,22
7

273,asintomatico,9,16487823C,0
106,inmune,4,26310305F,45
590,asintomatico,18,4453306T,1
234,asintomatico,8,15737838L,95
57,asintomatico,3,35711865H,13
260,inmune,9,36173243Q,79
322,asintomatico,11,32521315M,0
413,asintomatico,13,67426287Q,101
82,asintomatico,3,77836523S,42
96,asintomatico,3,41311551D,27
649,sintomatico,20,67207271Y,4

98,asintomatico,3,3565306F,80
150,asintomatico,5,88202047Z,49
284,inmune,9,27541308G,68
160,sintomatico,5,34640048R,35
641,asintomatico,20,35467260H,46
721,inmune,22,32421575Q,41
179,asintomatico,6,52053517D,87
660,asintomatico,20,25326314W,83
552,inmune,17,47544A,100
123,sintomatico,5,46411628C,5
60,asintomatico,3,45544378P,62
549,asintomatico,17,86350122A,50
26,asintomatico,2,72170843V,35
471,asintomatico,15,3443532H,56
280,sintomatico,9,57384542W,12
194,inmune,7,5882521H,11
204,asintomatico,7,43033418G,98
55,inmune,3,44554301N,46
22,inmune,2,68000253V,68
184,asintomatico,6,2862315B,86
267,asintomatico,9,5002021G,8
220,asintomatico,8,47047687Z,18
3,asin

--------
 
 
25
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
25,0,682,24
430,asintomatico,13,77855386H,94
683,asintomatico,21,11670730R,22
787,asintomatico,23,48804267S,98
100,inmune,3,82418868R,80
641,asintomatico,20,35467260H,46
691,inmune,21,65828182C,72
674,sintomatico,20,38641502F,55

747,asintomatico,22,86800435E,27
211,asintomatico,7,12726860V,31
339,asintomatico,11,52627435P,42
173,inmune,6,6466528D,76
618,asintomatico,19,15135202Y,30
460,asintomatico,15,21515768G,79
357,asintomatico,11,65216833B,37
756,sintomatico,22,86640234Q,14

231,inmune,8,2263870A,10
415,asintomatico,13,85344130P,10
44,asintomatico,2,65608264M,75
161,inmune,5,54667005F,4
117,asintomatico,5,50181243G,38
51,asintomatico,3,20570737C,92
108,asintomatico,5,14220578T,37
142,inmune,5,3604031T,105
422,asintomatico,13,4344161J,53
290,sintomatico,9,12623048G,53
125,inmune,5,30812658H,0
36,inmune,2,78366765S,54
748,asintomatico,22,88351107B,58
417,inmune,13,20717372F,49
245,sintomatico,8

715,asintomatico,21,57144740K,98
616,inmune,19,33860007M,47
383,inmune,12,23278073A,5
194,inmune,7,5882521H,11
433,asintomatico,14,51126731P,27
334,inmune,11,81060175X,62
674,sintomatico,20,38641502F,55
187,asintomatico,6,84483407Z,33
332,inmune,11,56481683P,93
783,inmune,23,55154250C,102
712,inmune,21,3235362K,65
351,asintomatico,11,24185208H,65
569,asintomatico,18,41226550Q,42
580,asintomatico,18,61087185J,3
717,asintomatico,22,60872252S,77
26,inmune,2,72170843V,35
728,sintomatico,22,60151161C,2
681,sintomatico,21,1172646Z,33
749,inmune,22,57478147C,40
430,asintomatico,13,77855386H,94
274,asintomatico,9,6271152H,14
537,asintomatico,17,56282136D,26
301,asintomatico,10,57240603C,62
732,inmune,22,74767542Q,65

168,inmune,6,33821783F,96
285,inmune,9,18885316Q,1
210,sintomatico,7,633621V,2
485,inmune,16,58364804G,37
795,inmune,23,84333865H,100
548,asintomatico,17,43781426Y,63
160,sintomatico,5,34640048R,35
63,inmune,3,55234511B,27
358,asintomatico,11,33077340M,23
11,inmune,1,34837711W,34


516,asintomatico,16,57531232K,54
609,asintomatico,19,74768710B,99
321,inmune,11,8054687H,14
155,asintomatico,5,41683137F,102
270,inmune,9,85231080A,104
175,asintomatico,6,53015428Z,55
726,inmune,22,76401153Y,103
486,inmune,16,23620161N,67
714,inmune,21,36200883X,43
478,sintomatico,15,24656736T,59
762,inmune,22,62763078B,15
96,asintomatico,3,41311551D,27
564,asintomatico,18,6003774S,64
58,inmune,3,35850015F,98
397,sintomatico,13,88641310T,36
199,inmune,7,17632223D,47

378,asintomatico,12,35262317M,100
313,sintomatico,10,5077360H,3

286,sintomatico,9,18056418S,48
332,inmune,11,56481683P,93
289,inmune,9,36525418S,11
610,asintomatico,19,73333116P,20
651,inmune,20,1475712D,18
49,asintomatico,3,3600786K,72
344,inmune,11,34116508X,51
31,inmune,2,21370246A,11
391,sintomatico,13,36815400J,108
33,inmune,2,83530566V,21
135,inmune,5,22766220S,4
450,inmune,14,58827017D,21
484,asintomatico,15,5478571V,5
511,asintomatico,16,7737020G,51
325,sintomatico,11,25234050Z,91
3,inmune,0,16772702K,71
520,inmun

597,muerto,18,77320764P,75
624,muerto,20,45650242A,107
631,muerto,20,41784118H,85
638,muerto,20,16257716M,67
639,muerto,20,56747576K,49
645,muerto,20,51248248Q,109
653,muerto,20,31448805P,98
657,muerto,20,87420817W,77
659,muerto,20,80804752W,79
665,muerto,20,74655483J,96
676,muerto,20,27400810J,79
678,muerto,20,47462871W,16
686,muerto,21,46863535T,82
697,muerto,21,64743570L,74
703,muerto,21,35845665G,9
711,muerto,21,75413680S,99
716,muerto,21,73211848L,78
727,muerto,22,87418784Q,70
745,muerto,22,56036852C,108
746,muerto,22,66634801Y,109
755,muerto,22,63868036A,91
764,muerto,22,14305422C,101
769,muerto,22,12822071P,22
776,muerto,23,36762002K,94
780,muerto,23,48146311C,67
790,muerto,23,7702770R,36
799,muerto,23,82575530X,76
 
 
--------
Total de vivos:670
Total de vivos:670
Total de vivos:670
--------
 
 
28
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
28,0,669,24
677,inmune,20,77033654F,29
546,inmune,17,61363166V,71
220,asintomatico,8,47047687Z,18
219,inmune

366,inmune,12,66057584C,74
13,inmune,1,40467652A,97
532,asintomatico,17,20566883F,87
777,asintomatico,23,32211330Z,75
606,inmune,19,77440732P,24
332,inmune,11,56481683P,93
126,inmune,5,71217013C,3
456,inmune,14,66236837B,26
748,inmune,22,88351107B,58
743,asintomatico,22,2656474C,18
747,inmune,22,86800435E,27
309,asintomatico,10,82458843W,43
198,inmune,7,11736168G,19
139,sintomatico,5,18716284B,2
646,inmune,20,51804518P,59
320,asintomatico,11,36360533V,89
400,asintomatico,13,70165478E,56
573,inmune,18,65820060V,64
256,sintomatico,9,45334736B,35
371,inmune,12,55810733Z,49
148,inmune,5,50144338Z,27
507,inmune,16,64652807Z,88
615,inmune,19,67008382K,43
583,inmune,18,75306187R,4

734,asintomatico,22,70000332Q,33
594,inmune,18,33308730S,97
184,asintomatico,6,2862315B,86
752,asintomatico,22,12223866X,31
760,inmune,22,11180366C,91
154,inmune,5,31614480Z,17
459,inmune,15,26014820A,49
393,inmune,13,8070715S,82
402,inmune,13,60314775N,73
157,inmune,5,46503858C,12
97,asintomatico,3,38524601S,46
26

795,inmune,23,84333865H,100
734,asintomatico,22,70000332Q,33
318,asintomatico,11,14532658Q,35
797,inmune,23,20746365C,43
317,inmune,11,81718070J,25
176,inmune,6,24826480G,46
88,inmune,3,31037240M,54

158,inmune,5,51083523V,37
334,inmune,11,81060175X,62
590,inmune,18,4453306T,1
785,asintomatico,23,10783871E,86
528,inmune,17,84444257X,61
483,inmune,15,53135616G,106
506,asintomatico,16,66654055D,84
389,inmune,12,81337611C,69
781,asintomatico,23,47788014V,58
115,inmune,5,78125530G,3
540,inmune,17,56058176T,21
312,inmune,10,84426717L,96
220,inmune,8,47047687Z,18
666,inmune,20,20515723E,8
729,inmune,22,44704886Q,71
126,inmune,5,71217013C,3
470,asintomatico,15,503605C,53
485,inmune,16,58364804G,37
381,inmune,12,6384740D,96
633,inmune,20,83270536W,99
22,inmune,2,68000253V,68
574,asintomatico,18,61208065M,52
744,inmune,22,35444651H,75
720,inmune,22,25811265K,107
377,inmune,12,16444240E,65
743,asintomatico,22,2656474C,18
611,inmune,19,46520317B,76
256,sintomatico,9,45334736B,35
63,inmune,3,55234

651,inmune,20,1475712D,18
282,inmune,9,13243400T,54
472,asintomatico,15,50004015Z,3
726,inmune,22,76401153Y,103
603,inmune,19,73458551R,53
732,inmune,22,74767542Q,65
5,inmune,0,73024747T,107
55,inmune,3,44554301N,46
259,inmune,9,25360842F,102
238,inmune,8,40457312J,23
501,inmune,16,12071528R,18
307,inmune,10,53674668M,74
133,inmune,5,60421441G,11
316,inmune,11,4712408F,30
533,inmune,17,36015627L,61
604,inmune,19,41056208N,3

94,inmune,3,65162407A,25
737,asintomatico,22,72743210Y,91
285,inmune,9,18885316Q,1
2,inmune,0,5482754Z,45
771,inmune,22,17200354B,20
134,inmune,5,12232543Q,48
312,inmune,10,84426717L,96
61,inmune,3,41688821X,100
252,inmune,9,8675453Z,36
359,inmune,11,72663238M,22
224,inmune,8,62806253S,3
488,inmune,16,30117177B,102
684,inmune,21,17206678X,37
770,inmune,22,8542034H,40
649,sintomatico,20,67207271Y,4
673,inmune,20,80522578S,65
300,inmune,10,1330851W,77
226,inmune,8,48872381A,70
82,inmune,3,77836523S,42
193,inmune,7,26526044Y,56
707,inmune,21,24402224Y,27
381,inmune,12

331,inmune,11,75033435Y,79
629,inmune,20,4764231B,74
351,inmune,11,24185208H,65
267,inmune,9,5002021G,8

240,inmune,8,50134113R,82
403,asintomatico,13,83500677M,90
305,inmune,10,33503741D,34
465,inmune,15,67833287P,66
54,inmune,3,33333164T,65
617,inmune,19,66356267W,31
20,asintomatico,2,57225015A,82
688,inmune,21,42861478N,55
557,inmune,17,11450546L,103
598,asintomatico,18,48213246W,109
278,inmune,9,47138042W,66
227,inmune,8,28576548Z,37
97,inmune,3,38524601S,46
531,inmune,17,23280882Y,15
715,inmune,21,57144740K,98
683,asintomatico,21,11670730R,22
244,inmune,8,21806043L,19
599,inmune,18,48305860H,40
417,inmune,13,20717372F,49
234,inmune,8,15737838L,95
706,inmune,21,67580082X,0
44,inmune,2,65608264M,75
85,inmune,3,51122384P,8
768,inmune,22,14503586Q,34
357,inmune,11,65216833B,37
698,inmune,21,66524545N,71
329,inmune,11,70681520J,102
618,inmune,19,15135202Y,30
39,inmune,2,25307720S,18
248,inmune,9,71130426M,56
734,inmune,22,70000332Q,33
294,inmune,10,84307236T,68
610,inmune,19,73333116P,

294,inmune,10,84307236T,68
256,sintomatico,9,45334736B,35
508,inmune,16,48210667E,34
441,inmune,14,24781086N,56
18,inmune,2,45852444N,95
141,inmune,5,52302031P,15
709,inmune,21,40223030D,44
579,inmune,18,16586621X,89
516,inmune,16,57531232K,54
275,inmune,9,50348203F,89
744,inmune,22,35444651H,75
725,asintomatico,22,44582018Z,71
574,inmune,18,61208065M,52
634,inmune,20,54138728V,20
757,inmune,22,61866667W,30
276,inmune,9,56481150G,0
789,inmune,23,13252560Y,8
143,inmune,5,11448883N,90
160,inmune,5,34640048R,35
485,inmune,16,58364804G,37

573,inmune,18,65820060V,64
253,sintomatico,9,58875344J,5
115,inmune,5,78125530G,3
73,inmune,3,67377527Q,84
169,inmune,6,66288721F,21
655,inmune,20,34507734Y,85
125,inmune,5,30812658H,0
180,inmune,6,3233842L,94
357,inmune,11,65216833B,37
265,inmune,9,30452570H,18
63,inmune,3,55234511B,27
195,inmune,7,2448761C,78
310,inmune,10,10422267R,108
159,inmune,5,7422340X,74
730,inmune,22,18720748J,24
541,inmune,17,23044423X,27
717,inmune,22,60872252S,77
121,inmune,

566,inmune,18,88804531J,86
617,inmune,19,66356267W,31
620,inmune,19,80268668W,60
35,inmune,2,72702531Z,7
560,inmune,18,87225484P,7
115,inmune,5,78125530G,3
281,inmune,9,87348175V,32
494,inmune,16,82184732M,84
371,inmune,12,55810733Z,49
37,inmune,2,88021316V,25
276,inmune,9,56481150G,0

535,inmune,17,47525225A,31
465,inmune,15,67833287P,66
736,inmune,22,5031642R,70
2,inmune,0,5482754Z,45
546,inmune,17,61363166V,71
702,inmune,21,54061678V,55
287,inmune,9,47252266P,52
26,inmune,2,72170843V,35
754,inmune,22,40876731G,45
72,inmune,3,16724205P,99
394,inmune,13,73170262V,29
695,inmune,21,87017841D,74
284,inmune,9,27541308G,68
425,inmune,13,66454234N,48
22,inmune,2,68000253V,68
314,inmune,10,8134074D,15
302,inmune,10,30146520Y,9
796,inmune,23,80578453T,33
20,asintomatico,2,57225015A,82
82,inmune,3,77836523S,42
668,inmune,20,65156472W,34
580,inmune,18,61087185J,3
321,inmune,11,8054687H,14
759,inmune,22,12370856F,36
253,inmune,9,58875344J,5
723,inmune,22,807028G,14
296,inmune,10,70238843V,51
634

743,inmune,22,2656474C,18
232,inmune,8,14855377E,81
629,inmune,20,4764231B,74
157,inmune,5,46503858C,12
512,inmune,16,75105125M,90
513,inmune,16,80673627T,33
623,inmune,20,56052717S,8
333,inmune,11,37083732G,57
728,inmune,22,60151161C,2
603,inmune,19,73458551R,53
226,inmune,8,48872381A,70

293,inmune,10,5548602J,16
255,inmune,9,50277424E,28
600,inmune,18,15140333P,61
704,inmune,21,56764584D,3
783,inmune,23,55154250C,102
584,inmune,18,23462113C,90
669,inmune,20,84437277E,107
668,inmune,20,65156472W,34
532,inmune,17,20566883F,87
479,inmune,15,20472517X,29
116,inmune,5,14233722B,12
522,inmune,17,88813331G,69
405,inmune,13,28202185E,75
503,inmune,16,63086638F,92
796,inmune,23,80578453T,33
747,inmune,22,86800435E,27
459,inmune,15,26014820A,49
360,inmune,11,70316188J,97
670,inmune,20,55245670S,8
338,inmune,11,56483744E,31
275,inmune,9,50348203F,89
278,inmune,9,47138042W,66
490,inmune,16,50081101G,109
535,inmune,17,47525225A,31
625,inmune,20,41515185R,101
611,inmune,19,46520317B,76
606,inmune

158,inmune,5,51083523V,37
196,inmune,7,85711525R,47
622,inmune,20,30085330L,0
628,inmune,20,82885713S,5
568,inmune,18,26412006W,109
35,inmune,2,72702531Z,7
717,inmune,22,60872252S,77
353,inmune,11,58161703Q,41
172,inmune,6,11067433V,0
483,inmune,15,53135616G,106
42,inmune,2,65808476W,54
334,inmune,11,81060175X,62
347,inmune,11,84001154W,40
770,inmune,22,8542034H,40

720,inmune,22,25811265K,107
490,inmune,16,50081101G,109
522,inmune,17,88813331G,69
641,inmune,20,35467260H,46
388,inmune,12,20418104S,3
242,inmune,8,40521727M,2
456,inmune,14,66236837B,26
601,inmune,18,6465503L,22
707,inmune,21,24402224Y,27
612,inmune,19,78342744Y,29
529,inmune,17,61105020T,70
273,inmune,9,16487823C,0
795,inmune,23,84333865H,100
523,inmune,17,3161504Q,94
213,inmune,7,40767854D,0
135,inmune,5,22766220S,4
723,inmune,22,807028G,14
322,inmune,11,32521315M,0
56,inmune,3,15043060W,103
767,inmune,22,38161657B,56
517,inmune,16,83320560R,41
569,inmune,18,41226550Q,42
220,inmune,8,47047687Z,18
261,inmune,9,26624476K,

716,muerto,21,73211848L,78
727,muerto,22,87418784Q,70
745,muerto,22,56036852C,108
746,muerto,22,66634801Y,109
755,muerto,22,63868036A,91
764,muerto,22,14305422C,101
769,muerto,22,12822071P,22
776,muerto,23,36762002K,94
780,muerto,23,48146311C,67
790,muerto,23,7702770R,36
799,muerto,23,82575530X,76
 
 
--------
Total de vivos:667
Total de vivos:667
Total de vivos:667
--------
 
 
37
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
37,0,667,24
417,inmune,13,20717372F,49
440,inmune,14,34576715X,65
113,inmune,5,22123455P,100
767,inmune,22,38161657B,56
384,inmune,12,72341173D,53
354,inmune,11,48270514T,100
391,inmune,13,36815400J,108

695,inmune,21,87017841D,74
31,inmune,2,21370246A,11
625,inmune,20,41515185R,101
730,inmune,22,18720748J,24
646,inmune,20,51804518P,59
351,inmune,11,24185208H,65
336,inmune,11,86866525X,4
402,inmune,13,60314775N,73

409,inmune,13,3375445B,13
340,inmune,11,16151626Z,83
135,inmune,5,22766220S,4
520,inmune,17,85354043P,1
279,inmune,9,35232

664,inmune,20,28387105E,29
311,inmune,10,3800046D,100
671,inmune,20,13067242E,64
139,inmune,5,18716284B,2
126,inmune,5,71217013C,3

570,inmune,18,41441485Q,77
636,inmune,20,4727565F,32
635,inmune,20,81076160X,60
152,inmune,5,57200150R,28
571,inmune,18,35165801C,3
328,inmune,11,41426211Z,87
474,inmune,15,10310870Q,17
36,inmune,2,78366765S,54
429,inmune,13,87505714Y,76
290,inmune,9,12623048G,53
251,inmune,9,33364437Q,12
507,inmune,16,64652807Z,88
707,inmune,21,24402224Y,27
739,inmune,22,25727775K,24
692,inmune,21,37047534P,79
651,inmune,20,1475712D,18
52,inmune,3,48423534R,25
439,inmune,14,13715512Z,87
5,inmune,0,73024747T,107
643,inmune,20,48166148P,68
252,inmune,9,8675453Z,36
267,inmune,9,5002021G,8
469,inmune,15,44434187G,77

694,inmune,21,84286180N,98
709,inmune,21,40223030D,44
740,inmune,22,51306538R,29
300,inmune,10,1330851W,77
363,inmune,12,75886208P,23
339,inmune,11,52627435P,42
206,inmune,7,88225347S,108
465,inmune,15,67833287P,66
13,inmune,1,40467652A,97
473,inmune,15,37748884L

792,inmune,23,85213048A,60
57,inmune,3,35711865H,13
169,inmune,6,66288721F,21
48,inmune,2,76521537P,20
429,inmune,13,87505714Y,76
171,inmune,6,11376657Y,67
19,inmune,2,58256723T,1
372,inmune,12,41036521J,65
677,inmune,20,77033654F,29
408,inmune,13,66570868J,54
360,inmune,11,70316188J,97
20,inmune,2,57225015A,82
720,inmune,22,25811265K,107
446,inmune,14,55613226P,98
516,inmune,16,57531232K,54
662,inmune,20,15207748X,33
562,inmune,18,15872480L,91
710,inmune,21,23617710E,109
482,inmune,15,38765371K,17
417,inmune,13,20717372F,49
520,inmune,17,85354043P,1
757,inmune,22,61866667W,30
698,inmune,21,66524545N,71

307,inmune,10,53674668M,74
343,inmune,11,87754888K,12
259,inmune,9,25360842F,102
251,inmune,9,33364437Q,12
413,inmune,13,67426287Q,101
577,inmune,18,18654632E,59
788,inmune,23,42171634F,16
228,inmune,8,25006358E,27
656,inmune,20,42148522X,109
279,inmune,9,35232327F,89
31,inmune,2,21370246A,11
138,inmune,5,87151463R,15
183,inmune,6,26202006S,109
695,inmune,21,87017841D,74
420,inmune,13,

719,inmune,22,72755308Y,30
106,inmune,4,26310305F,45
219,inmune,8,50850818A,90
677,inmune,20,77033654F,29
720,inmune,22,25811265K,107
55,inmune,3,44554301N,46
46,inmune,2,7645371X,64
192,inmune,6,33258553R,9

559,inmune,17,31671174J,46
569,inmune,18,41226550Q,42
450,inmune,14,58827017D,21
216,inmune,8,83711525N,84
600,inmune,18,15140333P,61
79,inmune,3,533082B,42
32,inmune,2,57815433B,80
570,inmune,18,41441485Q,77
578,inmune,18,7072028B,29
732,inmune,22,74767542Q,65
249,inmune,9,37286006Q,100
344,inmune,11,34116508X,51
152,inmune,5,57200150R,28
757,inmune,22,61866667W,30
2,inmune,0,5482754Z,45
37,inmune,2,88021316V,25
747,inmune,22,86800435E,27
771,inmune,22,17200354B,20
402,inmune,13,60314775N,73
460,inmune,15,21515768G,79
73,inmune,3,67377527Q,84
646,inmune,20,51804518P,59
731,inmune,22,17066652P,99
712,inmune,21,3235362K,65
122,inmune,5,40720386J,86
244,inmune,8,21806043L,19
794,inmune,23,47812187V,33
1,inmune,0,50160011R,4
714,inmune,21,36200883X,43
291,inmune,10,24670880E,62
366,i

219,inmune,8,50850818A,90
166,inmune,6,53127464V,18
651,inmune,20,1475712D,18

723,inmune,22,807028G,14
332,inmune,11,56481683P,93
626,inmune,20,37685176K,44
246,inmune,8,1774414X,39
101,inmune,3,68845357D,11
534,inmune,17,11004047L,77
709,inmune,21,40223030D,44
797,inmune,23,20746365C,43
772,inmune,22,46026578J,55
71,inmune,3,25645002W,59
212,inmune,7,41014451T,46
396,inmune,13,2714666E,47
562,inmune,18,15872480L,91
594,inmune,18,33308730S,97
117,inmune,5,50181243G,38
354,inmune,11,48270514T,100
669,inmune,20,84437277E,107
477,inmune,15,3235624F,53
554,inmune,17,67115534Q,56
175,inmune,6,53015428Z,55
207,inmune,7,65528316M,7
381,inmune,12,6384740D,96
93,inmune,3,81106371E,57
512,inmune,16,75105125M,90

667
 
 
--------
 
 
Total de muertos:133
6,muerto,0,18318322H,73
10,muerto,1,84781288E,78
15,muerto,2,36121484F,104
29,muerto,2,62033464A,36
30,muerto,2,56473453N,101
41,muerto,2,55825572H,40
47,muerto,2,12176403L,86
53,muerto,3,42580263H,74
59,muerto,3,26024564H,66
62,muerto,3,3786165

 
--------
Total de vivos:667
Total de vivos:667
Total de vivos:667
--------
 
 
43
[ 7  8 34 57  2 55 30 23 31 44 25 46 29 42 26 26 35 40 42 19 59 37 59 24]
43,0,667,24
21,inmune,2,37047443D,104
228,inmune,8,25006358E,27
416,inmune,13,28331387X,22
690,inmune,21,37235880F,99
189,inmune,6,54531517N,32
651,inmune,20,1475712D,18
190,inmune,6,718251F,53

367,inmune,12,61430630E,59
397,inmune,13,88641310T,36
357,inmune,11,65216833B,37
181,inmune,6,57634810F,6
752,inmune,22,12223866X,31
584,inmune,18,23462113C,90
201,inmune,7,54844003C,103
417,inmune,13,20717372F,49

664,inmune,20,28387105E,29
25,inmune,2,23628386A,18
2,inmune,0,5482754Z,45
644,inmune,20,47646551G,79
718,inmune,22,54667266S,26
90,inmune,3,10856433L,54
709,inmune,21,40223030D,44
567,inmune,18,54726344Y,96
470,inmune,15,503605C,53
141,inmune,5,52302031P,15
434,inmune,14,68733200T,60
289,inmune,9,36525418S,11
112,inmune,5,40124024H,24
220,inmune,8,47047687Z,18
338,inmune,11,56483744E,31
37,inmune,2,88021316V,25
591,inmune,18,20

186,inmune,6,46524077E,79
548,inmune,17,43781426Y,63
357,inmune,11,65216833B,37
95,inmune,3,62184416Y,52
563,inmune,18,17047725X,46
344,inmune,11,34116508X,51
411,inmune,13,80705542Z,2
517,inmune,16,83320560R,41
20,inmune,2,57225015A,82
320,inmune,11,36360533V,89

622,inmune,20,30085330L,0
773,inmune,22,1413040N,40
429,inmune,13,87505714Y,76
105,inmune,3,28115443J,0
788,inmune,23,42171634F,16
241,inmune,8,71748562Q,96
315,inmune,10,44112037S,51
590,inmune,18,4453306T,1
596,inmune,18,57317621B,99
301,inmune,10,57240603C,62
601,inmune,18,6465503L,22
155,inmune,5,41683137F,102
273,inmune,9,16487823C,0
739,inmune,22,25727775K,24
307,inmune,10,53674668M,74
46,inmune,2,7645371X,64
642,inmune,20,44021524F,72
491,inmune,16,15773058A,29
349,inmune,11,85443441M,51
37,inmune,2,88021316V,25
367,inmune,12,61430630E,59
793,inmune,23,37742808S,40
436,inmune,14,16046330N,93
58,inmune,3,35850015F,98
294,inmune,10,84307236T,68
178,inmune,6,2863010Q,6
306,inmune,10,77511674H,23
553,inmune,17,27407723A,19

682,inmune,21,82734538L,37
310,inmune,10,10422267R,108
760,inmune,22,11180366C,91
291,inmune,10,24670880E,62
313,inmune,10,5077360H,3
249,inmune,9,37286006Q,100
532,inmune,17,20566883F,87
670,inmune,20,55245670S,8
113,inmune,5,22123455P,100
797,inmune,23,20746365C,43
187,inmune,6,84483407Z,33
526,inmune,17,53381038Q,30
477,inmune,15,3235624F,53

607,inmune,19,84746250J,107
98,inmune,3,3565306F,80
177,inmune,6,86410884E,44
499,inmune,16,75522288V,106
88,inmune,3,31037240M,54
579,inmune,18,16586621X,89
1,inmune,0,50160011R,4
629,inmune,20,4764231B,74
380,inmune,12,72470108Y,32
358,inmune,11,33077340M,23
675,inmune,20,82142540H,3
698,inmune,21,66524545N,71
89,inmune,3,86030854K,109
456,inmune,14,66236837B,26
115,inmune,5,78125530G,3
648,inmune,20,83626661H,63
398,inmune,13,42528755F,103
619,inmune,19,22074864Q,24
627,inmune,20,27868035Q,7
186,inmune,6,46524077E,79
34,inmune,2,17735572L,98
425,inmune,13,66454234N,48
700,inmune,21,78101844P,27
365,inmune,12,68386413F,7
326,inmune,11,7083538

28,inmune,2,42587584W,13
137,inmune,5,75812234W,105
214,inmune,7,75304148D,40
39,inmune,2,25307720S,18
313,inmune,10,5077360H,3
781,inmune,23,47788014V,58

656,inmune,20,42148522X,109
699,inmune,21,70830840V,104
558,inmune,17,5480211R,1
752,inmune,22,12223866X,31
160,inmune,5,34640048R,35
75,inmune,3,67514254P,97
293,inmune,10,5548602J,16
405,inmune,13,28202185E,75
343,inmune,11,87754888K,12
505,inmune,16,63730081W,36
622,inmune,20,30085330L,0
494,inmune,16,82184732M,84
224,inmune,8,62806253S,3
44,inmune,2,65608264M,75
411,inmune,13,80705542Z,2
567,inmune,18,54726344Y,96
650,inmune,20,84565527R,87
580,inmune,18,61087185J,3
633,inmune,20,83270536W,99
282,inmune,9,13243400T,54
110,inmune,5,81034501G,8
385,inmune,12,40122470M,33
617,inmune,19,66356267W,31
573,inmune,18,65820060V,64
311,inmune,10,3800046D,100
517,inmune,16,83320560R,41
89,inmune,3,86030854K,109
640,inmune,20,37527658F,66
11,inmune,1,34837711W,34
470,inmune,15,503605C,53
782,inmune,23,37735466X,22
309,inmune,10,82458843W,43

571,inmune,18,35165801C,3
401,inmune,13,76656020X,29
366,inmune,12,66057584C,74
724,inmune,22,54671717G,0
781,inmune,23,47788014V,58
757,inmune,22,61866667W,30
692,inmune,21,37047534P,79
752,inmune,22,12223866X,31
122,inmune,5,40720386J,86
449,inmune,14,57666825Y,93
233,inmune,8,71171301D,67
249,inmune,9,37286006Q,100
664,inmune,20,28387105E,29
481,inmune,15,48452484V,2
628,inmune,20,82885713S,5
468,inmune,15,33575178P,77

667
 
 
--------
 
 
Total de muertos:133
6,muerto,0,18318322H,73
10,muerto,1,84781288E,78
15,muerto,2,36121484F,104
29,muerto,2,62033464A,36
30,muerto,2,56473453N,101
41,muerto,2,55825572H,40
47,muerto,2,12176403L,86
53,muerto,3,42580263H,74
59,muerto,3,26024564H,66
62,muerto,3,37861653L,101
66,muerto,3,75208683V,97
67,muerto,3,22001017E,86
68,muerto,3,38858567K,89
69,muerto,3,63350118E,109
70,muerto,3,2026656B,77
74,muerto,3,73464544Z,108
78,muerto,3,16172854J,97
80,muerto,3,73625082N,72
81,muerto,3,63507548V,88
87,muerto,3,10254348M,69
91,muerto,3,83726675M,102
99

474,inmune,15,10310870Q,17
587,inmune,18,72565417A,69
758,inmune,22,14343665Z,28
732,inmune,22,74767542Q,65
714,inmune,21,36200883X,43
333,inmune,11,37083732G,57
571,inmune,18,35165801C,3

300,inmune,10,1330851W,77
511,inmune,16,7737020G,51
250,inmune,9,3351635Y,46
589,inmune,18,86663415J,59
186,inmune,6,46524077E,79
397,inmune,13,88641310T,36
687,inmune,21,56183254G,97
86,inmune,3,68785164F,49

197,inmune,7,87550250Z,24
467,inmune,15,23268183A,24
57,inmune,3,35711865H,13
683,inmune,21,11670730R,22
700,inmune,21,78101844P,27
320,inmune,11,36360533V,89
237,inmune,8,23126453E,50
590,inmune,18,4453306T,1
442,inmune,14,63223150Z,24
743,inmune,22,2656474C,18
702,inmune,21,54061678V,55
670,inmune,20,55245670S,8
251,inmune,9,33364437Q,12
358,inmune,11,33077340M,23
156,inmune,5,60676673M,37
609,inmune,19,74768710B,99
541,inmune,17,23044423X,27
299,inmune,10,76042764A,82
349,inmune,11,85443441M,51
9,inmune,1,34803716R,54
181,inmune,6,57634810F,6
575,inmune,18,52317584J,59
450,inmune,14,58827017

458,inmune,14,12227122T,71
618,inmune,19,15135202Y,30
401,inmune,13,76656020X,29
554,inmune,17,67115534Q,56
696,inmune,21,46557043Y,26
12,inmune,1,86163243E,56
704,inmune,21,56764584D,3
637,inmune,20,28034082A,60
501,inmune,16,12071528R,18
309,inmune,10,82458843W,43
520,inmune,17,85354043P,1
642,inmune,20,44021524F,72
24,inmune,2,5385786Z,3
230,inmune,8,81876522H,53
253,inmune,9,58875344J,5
299,inmune,10,76042764A,82
294,inmune,10,84307236T,68

8,inmune,1,76530624X,9
176,inmune,6,24826480G,46
455,inmune,14,15110137B,36
338,inmune,11,56483744E,31
524,inmune,17,43421240T,82
384,inmune,12,72341173D,53
575,inmune,18,52317584J,59
514,inmune,16,11610348V,20
585,inmune,18,74362015W,17
98,inmune,3,3565306F,80
156,inmune,5,60676673M,37
194,inmune,7,5882521H,11
614,inmune,19,62825443T,30
794,inmune,23,47812187V,33
495,inmune,16,255636Z,15
162,inmune,5,33714033N,57
391,inmune,13,36815400J,108
284,inmune,9,27541308G,68
589,inmune,18,86663415J,59
671,inmune,20,13067242E,64
459,inmune,15,26014820A,4

In [25]:
printearEdificio(MiSimulador.ciudad,0)

68,inmune,3,56711266M,22


In [26]:
printearciudad(MiSimulador.ciudad)

68,inmune,3,56711266M,22

22,inmune,1,44622371W,57
18,inmune,1,81356210N,8
76,inmune,4,88524085Y,59
23,inmune,1,86670864X,4
32,inmune,1,42454783A,11
20,inmune,1,53428358W,78
3,inmune,1,27102032M,34
83,inmune,4,77414261X,56
72,inmune,4,25210143G,20
30,inmune,1,58846701M,39
48,inmune,2,1162457Z,63
88,inmune,4,33846622Y,15
57,inmune,2,71436206T,22
11,inmune,1,48667561K,107
93,inmune,4,68352384H,80
4,inmune,1,11776370W,28
43,inmune,2,4277068B,35
98,inmune,5,46154545P,101
97,inmune,5,60588057P,32
19,inmune,1,15120414F,10
65,inmune,3,34372778Z,100

8,inmune,1,53054467E,46
36,inmune,2,26306750V,18
89,inmune,4,34758580Z,78
80,inmune,4,72888650V,86
67,inmune,3,86035467B,91
53,inmune,2,8833281Q,63
15,inmune,1,2846257F,85
50,inmune,2,13316802D,39
84,inmune,4,60008807J,36
2,inmune,1,43602763F,64
29,inmune,1,80645358K,47
55,inmune,2,41147331D,35
64,inmune,3,58076113D,101
44,inmune,2,3608884T,92
35,inmune,1,41825024F,92
59,inmune,2,30124532Y,9
78,inmune,4,18158546T,9
25,inmune,1,5302348C,34
79,inmun

In [27]:
MiSimulador.actualizar_catalogo()
for i in range(len(MiSimulador.CatalogoPersonas)):
                print(MiSimulador.CatalogoPersonas[i])
            

0,inmune,0,11243867H,25
1,inmune,1,56224405P,70
2,inmune,1,43602763F,64
3,inmune,1,27102032M,34
4,inmune,1,11776370W,28
5,inmune,1,87008361M,2
7,inmune,1,55601061X,7
8,inmune,1,53054467E,46
10,inmune,1,86644448K,22
11,inmune,1,48667561K,107
12,inmune,1,2470853D,48
13,inmune,1,24375770W,21
14,inmune,1,75147732Q,71
15,inmune,1,2846257F,85
18,inmune,1,81356210N,8
19,inmune,1,15120414F,10
20,inmune,1,53428358W,78
22,inmune,1,44622371W,57
23,inmune,1,86670864X,4
25,inmune,1,5302348C,34
28,inmune,1,82581208F,67
29,inmune,1,80645358K,47
30,inmune,1,58846701M,39
32,inmune,1,42454783A,11
33,inmune,1,76654370Q,35
34,inmune,1,63281802Q,48
35,inmune,1,41825024F,92
36,inmune,2,26306750V,18
37,inmune,2,50446516H,104
39,inmune,2,43800534R,6
41,inmune,2,40557607M,49
42,inmune,2,76482600X,35
43,inmune,2,4277068B,35
44,inmune,2,3608884T,92
45,inmune,2,47076434B,42
47,inmune,2,61775203D,34
48,inmune,2,1162457Z,63
49,inmune,2,11447256H,44
50,inmune,2,13316802D,39
51,inmune,2,16025612V,56
53,inmune,2,88332

In [28]:
personitaputa=MiSimulador.cogerpersona(0)
print(personitaputa.contadorInfecciones)

4


In [167]:
MiSimulador=Simulador(100,10) 
print(MiSimulador.capacidades)
print(len(MiSimulador.ciudad))

[23  1 29  7 22 16  2]
0,sano,0,87204200E,7
1,sano,0,81351675P,65
2,sano,0,7541462S,84
3,sano,0,2734837E,49
4,sano,0,67118311X,62
5,sano,0,63653820D,41
6,sano,0,56840305Z,104
7,sano,0,71438685H,88
8,sano,0,37235031D,2
9,sano,0,24211256F,28
10,sano,0,76816004Y,83
11,sano,0,25172814G,49
12,sano,0,75582883F,33
13,sano,0,65767330A,93
14,sano,0,22875655Q,88
15,sano,0,11256111A,85
16,sano,0,87500174D,37
17,sano,0,23444251Y,63
18,sano,0,50162442V,58
19,sano,0,52664477C,99
20,sano,0,10176827V,22
21,sano,0,57341107Z,72
22,sano,0,32625576F,67
23,sano,1,76036012J,70
24,sano,2,26170230W,84
25,sano,2,30847235A,11
26,sano,2,78242507A,47
27,sano,2,12318218Q,13
28,sano,2,3440412A,53
29,sano,2,32441324P,31
30,sano,2,26126301A,94
31,sano,2,28610526K,51
32,sano,2,27767452N,105
33,sano,2,50417272F,78
34,sano,2,2504088D,32
35,sano,2,57177760J,40
36,sano,2,31066118H,88
37,sano,2,76265586R,79
38,sano,2,68173116N,58
39,sano,2,35280872E,52
40,sano,2,34084064L,36
41,sano,2,6287818D,23
42,sano,2,11550463R,81
43,